### ISSUE TITLE
My cache notes do not work

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1400] opened 2018-02-08 10:29 UTC
After last changes "My cache notes"do not work on OCNL and OCRO. There is a white screen.
Perhaps helpful to mention is that the standard favicon is shown on this page.

![selectie_134](https://user-images.githubusercontent.com/1060518/35968108-316c2f6a-0cc3-11e8-9e51-311d9bd48b60.png)

**Comment by kojoty** [comment] 2018-02-08 10:35
hmm.. @harrieklomp, I need more info. It works at my dev and oc.pl. 
Can you check your apache error.log. You can paste here or send me by email.

**Comment by andrixnet** [comment] 2018-02-09 15:09
At OCRO, error_log:

```
PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /serv
e/www/oc_ro/oc_www/Controllers/CacheNotesController.php on line 118, referer: ht
tp://www.opencaching.ro/
```

**Comment by andrixnet** [comment] 2018-02-09 15:15
Apparently this item in the new menu is the only one called with the new `SimpleRouter::getLink` at this time.

**Comment by andrixnet** [comment] 2018-02-09 15:20
Since the default favicon.ico is a file generically called by the browser, this file is unique at project level, not node level. 
the actual website icon as defined in config is generated in the HTML template of the page, which requires the PHP code to run correctly. 
In this case, it did not run, thus the error and the non-specific favicon. @harrieklomp it is expected behaviour. IMO no need to complicate things on this tiny detail.

**Comment by rapotek** [comment] 2018-02-10 23:25
@kojoty it seems to be the same problem as in my WatchlistItem: PHP 5.
I checked the code in php sandbox. The original:
`return ($row['coords'])->getAsText();`
works in 7.0.2 and 7.1.0 but gives ParseError in f.ex. 5.6.29.
Remove parentheses:
`return $row['coords']->getAsText();`
and it should work in 5.6 as well as 7.0 and 7.1

**Comment by kojoty** [comment] 2018-02-12 20:31
I hope this is fixed now - if not please reopen.

**Closed by kojoty** 2018-02-12 20:31 UTC
Labels: Component_ListOfCaches, Priority_Critical, Type_Defect
