### ISSUE TITLE
Error deleting log entry; translation in database

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#235] opened 2016-02-09 10:19 UTC
As owner of a cache, I try to delete a log entry I have made. 
http://www.opencaching.ro/viewcache.php?cacheid=295
http://www.opencaching.ro/removelog.php?logid=356

This is the error. 

```
string(17) "log doesn't exist"

→ Called from .../removelog.php:205 [removelog()]

    .../removelog.php:256 [removelog()]
```

Upon further investigation this query returns zero results: 

```
SELECT   `cache_logs`.`node` AS `node`, `cache_logs`.`uuid` AS `uuid`, `cache_logs`.`cache_id` AS `cache_id`, `caches`.`user_id` AS `cache_owner_id`,
                        `caches`.`name` AS `cache_name`, `cache_logs`.`text` AS `log_text`, `cache_logs`.`type` AS `log_type`,
                        `cache_logs`.`user_id` AS `log_user_id`, `cache_logs`.`date` AS `log_date`,
                        `log_types`.`icon_small` AS `icon_small`,
                        `log_types_text`.`text_listing` AS `text_listing`,
                        `user`.`username` as `log_username`
                     FROM `log_types`, `log_types_text`, `cache_logs`, `caches`, `user`
                    WHERE `cache_logs`.`id`='356'
                      AND `cache_logs`.`user_id`=`user`.`user_id`
                      AND `caches`.`cache_id`=`cache_logs`.`cache_id`
                      AND `log_types_text`.`log_types_id`=`log_types`.`id` AND `log_types_text`.`lang`='ro'
                        AND `cache_logs`.`deleted` = 0
                      AND `log_types`.`id`=`cache_logs`.`type`
```

while this query returns 1 result: 
```
SELECT * FROM cache_logs
WHERE `cache_logs`.`id`='356'
```

Further investigation yielded that table `log_types` has individual columns for each language and these values are used as strings. 
Furthermore, table `log_types_text` has a single column designating the language (**different structure entirely**) with no entries for lang='RO'. 

Thus the error is justified at database completeness level, but it shows that there are still several database tables containing translations that have not yet been moved to translation file.

I can do changing hardcoded strings to translation, but this is beyond me at this time.

**Comment by harrieklomp** [comment] 2016-02-09 15:39
I have added other languages (nl, de, ro) in both tables and did send them to Andrei as sql files. Perhaps this problem should be solved for oc.ro.

There are more tables i have modified. Is there a share site where all these files can be uploaded and/or be modified? A option is to share these files as .csv so other nodes can add their own language and own databases can be updated.

**Comment by wloczynutka** [comment] 2016-02-09 15:47
All transaltions should be removed from database. This is very bad practice to store translations in db. (As we can see in current isue caused by that bad practice)

Please do not add any transaltions to database tables. Move it to language files, then sql queries can be changed.

**Comment by harrieklomp** [comment] 2016-02-09 16:26
I know that (on oc.nl there are no errors because these translations are in db), this is only a temp. solution. Like Andrei i do not have the skills to change the code for this.

Perhaps a programmer has time to move these db translations to language files.

**Comment by wrygiel** [comment] 2016-02-09 17:39
This might be useful:

http://www.opencaching.ro/okapi/devel/dbstruct?compare_to=http://opencaching.pl/okapi/devel/dbstruct

**Comment by harrieklomp** [comment] 2016-02-09 18:46
When installing and/or using the Polish code and the database with use of the provided link from wrygiel there is assumed that there is only Polish and English language available (db). For example the mentioned tables `log_types` and `log_types_text` are from beginning only translated in Polish and English (and more tables). 

Some time ago i did make a test log on http://www.opencaching.ro/viewlogs.php?logid=355 and when i select sitelanguage Dutch i cannot remove this testlog. Now after selecting English language i get the page with the warning "Are you sure you want to delete your log?"
This shows me that the Romanian site cannot delete logs in their own language. When they select English or Polish language they can delete logs.

Just my two cents :-)

**Comment by wrygiel** [comment] 2016-02-09 18:58
> When installing and/or using the Polish code and the database with use of the provided link from wrygiel there is assumed that there is only Polish and English language available (db).

Do you mean that different OC servers have different database structures *on purpose*? If so, then I agree with @wloczynutka, it's awful and should be removed :)

**Comment by harrieklomp** [comment] 2016-02-09 19:04
No, we do not use different structures. oc.nl has only added their own and other languages to it. Let me show it with some pictures.

![selection_127](https://cloud.githubusercontent.com/assets/1060518/12927352/0dd98754-cf68-11e5-8026-0a31f96a1e0f.png)

![selection_128](https://cloud.githubusercontent.com/assets/1060518/12927359/18718676-cf68-11e5-8b5b-fa8496e63dab.png)

**Comment by wrygiel** [comment] 2016-02-09 19:09
> Because i did add these NL/nl parts in the Dutch database all works fine on oc.nl.

Okay, I understand now.

**Comment by wrygiel** [comment] 2016-02-09 19:13
> Please do not add any transaltions to database tables. Move it to language files, then sql queries can be changed.

@harrieklomp is not a developer, I don't think he will be able to change it. It's a good thing he managed to made it work for OCNL and I think @andrixnet can use a similar hack to make it work on OCRO. I agree that it's not a good solution, but since no one wants to change it, using such hacks seems to a good thing.

**Comment by harrieklomp** [comment] 2016-02-09 19:30
That is why i suggested (temporary) make use of a public (secured) site to share these tables where languages has to be added. This way all nodes can add provided languages in their databases.

The same errors will appear on OC.PL when deleting a log in other languages beside Polish and English. After a developer has implement a table in the code than this table can be removed from this shared site and the node itself.

**Comment by wrygiel** [comment] 2016-02-09 19:58
> That is why i suggested (temporary) make use of a public (secured) site to share these tables where languages has to be added. 

I guess we could also simply commit the contents of this table into the repo (`mysqldump`) and have them override the table after each upgrade (after `post-commit.php` is called)...

**Comment by wloczynutka** [comment] 2016-02-10 08:52
wysłane 5-01-2016. doreczone  7-01-2016. Dorzuciłem na drive zrzut
śledzenia przesyłki.

2016-02-09 20:58 GMT+01:00 Wojciech Rygielski <notifications@github.com>:

> That is why i suggested (temporary) make use of a public (secured) site to
> share these tables where languages has to be added.
>
> I guess we could also simply commit the contents of this table into the
> repo (mysqldump) and have them override the table after each upgrade
> (after post-commit.php is called)...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencaching/opencaching-pl/issues/235#issuecomment-182035938>
> .
>



-- 
__________________________________
*Andrzej 'Łza' Woźniak*

*(+48) 798 835 592*
skype praca: *andrzej.wozniak.traveltech*
skype dom: *wloczynutka*

**Comment by harrieklomp** [comment] 2016-02-10 15:13
@wrygiel Just show me what i need to do and i will move these modified tables into the repo.

- cache_size

- cache_status

- cache_type

- log_types

- log_types_text

- countries 

- waypoint_type

- languages

There are some translations not translated or wrong translated in these tables, but i will try to do this before i commit. For example table countries the column "pl" has German translations?

**Comment by wloczynutka** [comment] 2016-02-10 15:20
I woiuld prefer you do not do that. This just increase mess.  Better if you find all places in the code these translation are used. I will try to remove it permanently and use transaltion files.

**Comment by harrieklomp** [comment] 2016-02-10 16:29
This means that there is a lot of work to do. When i search for 'log_types' i find 50 files where this is used. When i search for 'log_types_text' i find 10 files.

When solving this issue the therms 'log_types' and 'log_types_text' are found in "removelog.php" file from line 10-22.

I do not know if changing this will solve this issue but it is worth trying.
When this issue is solved, people can delete logs on all nodes in different languages.  After that i can make a new issue for the remaining mentioned tables.

@wloczynutka If you can make time for this we all are greatfull to you :-)

**Comment by harrieklomp** [comment] 2016-02-10 16:34
BTW.
If i find a logic in programming these changes i could be able to give a helping hand.

**Comment by wloczynutka** [comment] 2016-02-11 13:59
I'm working on removelog.php (I'm performing deep refactoring of this script)

**Comment by harrieklomp** [comment] 2016-02-11 14:55
Great work :-)

**Comment by andrixnet** [comment] 2016-02-12 14:47
> I guess we could also simply commit the contents of this table into the repo (mysqldump) and have them override the table after each upgrade (after post-commit.php is called)...

This is definitely related to an enhancement I posted.

**Comment by andrixnet** [comment] 2016-02-12 14:49
I will try updated the romanian translation files this weekend. 
LZA is right about the proper way to do it. 

P.S. 
I think I will add hungarian translation sometime this spring (I am working with a friend who is native hungarian speaker).

**Comment by wrygiel** [comment] 2016-02-12 16:46
> LZA is right about the proper way to do it.

I agree! The solution described in my comment here https://github.com/opencaching/opencaching-pl/issues/235#issuecomment-182012807 is not the proper way, just the fast way. If you want to do it the proper way, then go for it :)

**Comment by andrixnet** [comment] 2016-03-09 16:09
Currently on OCRO I have updated the missing translations in the database as a quick fix. 
Thank you @harrieklomp for the help. 

However I believe this issue should remain open while this action still depends on translations from the database.

**Comment by wloczynutka** [comment] 2016-03-10 23:02
Fixed with https://github.com/opencaching/opencaching-pl/pull/323

**Closed by wloczynutka** 2016-03-10 23:02 UTC
Labels: Component_DataBase, Component_Translations
