### ISSUE TITLE
Database differences

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1164] opened 2017-08-30 11:05 UTC
After recent problems because of some incompatible database changes, using the OKAPI dbstruct tool I analyzed more of OCRO <-> OCPL differences and I've come across some discrepancies: 
OCUK <-> OCPL differences are even bigger and some are the same as for RO.
http://www.opencaching.ro/okapi/devel/dbstruct?compare_to=https://opencaching.pl/okapi/devel/dbstruct

- [ ] table `badge_area` does not exist on OCRO. Could not find any SQL Alter file to create it.
- [ ] table `badge_cache` does not exist on OCRO. Could not find any SQL Alter file to create it.
- [x] several `PowerTrail *` tables have additional indexes for which I cannot find SQL alter file to drop them
- [ ] table badges differs and I can't find these differences in any SQL alter file
- [x] tables `cache_type` and `cache_status` and `map_settings*` lack `ro` column at OCPL (semantically it is not needed, but for consistency it should have it)
- [ ] I can't find any SQL alter to add comments to wp_* columns in `caches`
- [ ] this part of `2014-03-29_issue-80.sql` was not run on OCPL or they were removed later (?)
```
alter table countries add column ro varchar(128) not null;
alter table countries add column list_default_ro int(1) not null default 0;
alter table countries add column sort_ro varchar(128) not null;
```
- [ ] I can't find any SQL alter for changes to table `gns_locations` 
- [ ] tables `pds_*` does not exist on OCRO. Could not find any SQL Alter file to create it.
- [ ] can't find SQL alter with index changes to `pictures` table
- [ ] can't find SQL alter on `user` table do drop `cog_note`
- [x] I'm not sure about the indexes of `powerTrail_caches`

I am not sure which of these differences are some OCPL specific or experimental stuff, which are missed changes or changes done without an SQL Alter file, which should be propagated to other nodes and which should not. 

**IMO each node should have an identical database structure.**

**Comment by kojoty** [comment] 2017-08-30 11:38
@tripper1971, can you explain the badge_* tables issues
@andrixnet 

>  several PowerTrail * tables have additional indexes for which I cannot find SQL alter file to drop them
ignore this - I'm working on complete powertrail refactoring so it will be redefined

> tables cache_type and cache_status and map_settings* lack ro column at OCPL (semantically it is not needed, but for consistency it should have it)

yes, this is an issue with translations in DB and we are aware of it - that why we disable ro support at OCPL - we should remove it all and I'm going to do that but I don't know when :(

**Comment by deg-pl** [comment] 2017-08-31 08:38
Problem with badges is related also with #1097

**Comment by deg-pl** [comment] 2017-09-14 18:28
@andrixnet I think issue #788 is a duplicate of this issue, and should be closed. What is your opinion?

**Comment by following5** [comment] 2019-01-27 00:53
The database differences for all *used* tables and columns are leveled by (100_init)[https://github.com/opencaching/opencaching-pl/blob/master/Utils/Database/Updates/100_init.php].  For cleanup of tables and columns that probably are not in use, there is the new issue #1899.

**Closed by following5** 2019-01-27 00:53 UTC
Labels: Component DataBase, Server DB Contents, Type Needs clarify (unknown)
