### ISSUE TITLE
User object defect

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#809] opened 2016-11-02 16:56 UTC
Viewing profile of non-existent user (i.e. https://opencaching.pl/viewprofile.php/?userid=10000000) generates blank page and error:

> PHP Catchable fatal error:  Argument 1 passed to lib\\Objects\\User\\User::setUserFieldsByUsedDbRow() must be of the type array, boolean given, called in /srv/ocpl/lib/Objects/User/User.php on line 97 and defined in /srv/ocpl/lib/Objects/User/User.php on line 205

**Comment by kojoty** [comment] 2017-06-18 21:42
seems to be fixed now...

**Closed by kojoty** 2017-06-18 21:42 UTC
Labels: Component_UserProfile, Priority_Medium, Type_Defect

**Comment by deg-pl** [comment] 2017-06-18 21:55
@kojoty I've checked https://opencaching.pl/viewprofile.php/?userid=10000000 and this page looks 'a little bit different' ;). Please - check it.
But you're right - now php doesn't generate error.

**Comment by kojoty** [comment] 2017-06-19 08:06
@deg-pl, 
the problem is in "/" in url:
https://opencaching.pl/viewprofile.php/?userid=10000000
check this
https://opencaching.pl/viewprofile.php?userid=10000000
and this
https://opencaching.pl/index.php/
