### ISSUE TITLE
Results of search are not displayed but query is called

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#2164] opened 2020-05-14 07:38 UTC
During searching a cache or user on our site sometimes table with results is not returned:
![image](https://user-images.githubusercontent.com/13780868/81905810-8fb01900-95c5-11ea-93cc-bda4d9d6cef9.png)

The number of results is visible so I believe results also are taken from DB but are not displayed.

It is also reproducible in another places like:

>  wejdźcie w profil dowolnego użytkownika, który zakłada skrzynki (na przykład w swój). Zjedźcie do sekcji "Statystyka liczbowa skrzynek założonych / Liczba wszystkich skrzynek użytkownika" i kliknijcie w przycisk [Pokaż]. 

In some cases issue is sporadic - sometimes works fine, sometimes not (for example for next search this should work). 
But for example for list of user caches (clicked from user profile) the reproduction is stable:
Example ->[click here](https://opencaching.pl/search.php?showresult=1&expert=0&output=HTML&sort=bycreated&ownerid=99784&cachetype=1111101111&searchbyowner=&f_inactive=0&f_ignored=0&f_userfound=0&f_userowner=0)

**Comment by mzylowski** [comment] 2020-05-14 07:47
Probably also this is a reason of another issue related with Badges:
![image](https://user-images.githubusercontent.com/13780868/81907359-e7e81a80-95c7-11ea-99f1-d0954bdeee52.png)

**Comment by rapotek** [comment] 2020-05-21 08:36
Looks like it's a problem with GCT.js. It is written in a synchronous way, i.e. it assumes that after `google.load('visualization', ...)` everything is available at once, while it is not always true.
The correct way should be a call of `google.setOnLoadCallback(the_whole_GCT_function)`, but with code organization in search templates, refactoring may be not trivial.

**Comment by andrixnet** [comment] 2020-06-14 18:55
I can confirm this issue on OCPL, OCNL, OCRO. 
Confirmed across multiple browsers: Firefox (2 versions), Chrome.
Confirmed with addons like Adblock and Privacy badger disabled.

Here is a bit from the browser console in Chrome:
```
GCT.js:179 Uncaught TypeError: Cannot read property 'DataTable' of undefined
    at new GCT (GCT.js:179)
```

Here is a bit as reported by Firefox console:
```

          TypeError: google.visualization is undefined[Learn More]  GCT.js:179:5
	GCT https://www.opencaching.ro/js/GCT.js:179:5
	<anonymous> https://www.opencaching.ro/search.php:285:15
...
TypeError: gct is undefined[Learn More]  search.php:323:1
	<anonymous> https://www.opencaching.ro/search.php:323:1
```
There are over 10 such errors.

GCT.js is loaded properly (analyzed in browser network console).

Considering what @rapotek says, how come it worked fine until recently and suddenly it won't work at all?

**Comment by kojoty** [comment] 2020-06-14 19:31
Jacek triPPer is working on this. It will be fixed soon.

**Comment by Amberel** [comment] 2020-06-18 17:14
I just posted this on the FB UK tehnical page and Andrei asked me to copy it here. Having major problems with search on OC UK, all of the search functions return the number of hits but no links to any of the caches. That is the quick search facility by the login button, the main search page, and even if I go to a different user and click to view their caches. I got one of the other admins to confirm it wasn't just my setup, and it wasn't - we are getting the problem on Windows, Mac, Firefox, Chrome etc. Maps appear still to work OK
Good luck on sorting it out, and many thanks for the work you guys do.
Rgds, Andy

**Comment by kojoty** [comment] 2020-06-18 17:19
Andy,

Issue is more challenging than we thought at the first sight.
These pages used Google charts API tables. Last days something was changed
in Google and it is not worked as before - there was some "hacks" on our
side and now we have a problem. Jacek (triPPer) is still working on this.

**Comment by Amberel** [comment] 2020-06-18 17:35
Many thanks for the update - wish I could help but this stuff is way over my head :-(

**Comment by andrixnet** [comment] 2020-06-22 08:53
Code stability question: does opencaching-pl implementation host locally all needed files or does it rely on Google CDN for it? 
i.e.
- one can host locally jquery.js, a given version, and have the website run stable based on that version
- one can refer jquery.js from CDN (not specifying version) and any update pushed by the CDN potentially breaking working code in the website

If the charts API is used according to the latter scenario, while fixing this issue can we make it so it runs accordin to the former scenario?

**Comment by rapotek** [comment] 2020-06-22 09:55
> Code stability question: does opencaching-pl implementation host locally all needed files or does it rely on Google CDN for it?
> i.e.
> 
>     * one can host locally jquery.js, a given version, and have the website run stable based on that version
> 
>     * one can refer jquery.js from CDN (not specifying version) and any update pushed by the CDN potentially breaking working code in the website
> 
> 
> If the charts API is used according to the latter scenario, while fixing this issue can we make it so it runs accordin to the former scenario?

Google API loader is retrieved remotely from gstatic.com, so it is a CDN. The same applies to another third party libraries, but those are exact versions in most cases.

This could be a solution (or a workaround rather), but the chart API in the loader itself loads desired packages and if it does that using remote sources, locally cached file will not improve the whole process. I did not analyse the loader, so I am not sure what is done in `google.charts.load` call.

Anyway I created a PR with a workaround, it works in my environment in functions and browsers where I am able to test it. Maybe it won't fix every usage for every user but should improve at least search results and stats for most.

**Comment by deg-pl** [comment] 2020-07-02 18:53
Fixed by @tripper1971. Thanks

**Closed by deg-pl** 2020-07-02 18:53 UTC
Labels: Component Search, Priority High, Type Defect
