### ISSUE TITLE
Mail auto archiving cache

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1621] opened 2018-09-13 12:42 UTC
All send mails from OC are now with new design. But mails with notifications about archiving caches are still the old way.
Are there plans to update these mails?
Sorry but this mail is in Dutch but it is clear what i mean.
![selectie_209](https://user-images.githubusercontent.com/1060518/45488871-064aa280-b763-11e8-8a90-4c645a1a3399.png)

**Comment by kojoty** [comment] 2018-09-13 13:00
we have no plans - it just needs a refactoring of this part of the code - if anyone do it - It will be done :)

**Comment by deg-pl** [comment] 2018-09-13 13:12
Duplicate of #1279

**Closed by deg-pl** 2018-09-13 13:12 UTC
Labels: Component_Emails, Priority_Medium, Type_Enhancement
