### ISSUE TITLE
c:geo not refresh the geocache due to limits introduced to OCPL endpoints

### ISSUE THREAD

**Issue by pawelko-g** [opencaching/opencaching-pl#2405] opened 2024-06-26 18:10 UTC
The c:geo program does not refresh the geocache in a given number, but only a few at a time.
![Screenshot_20240624_193135_cgeo](https://github.com/opencaching/opencaching-pl/assets/173948046/09dd020b-9060-4c45-88ac-ce542e368020)
![Screenshot_20240626_185038_cgeo](https://github.com/opencaching/opencaching-pl/assets/173948046/cb5b275b-e607-4ee8-93c6-2a7b239e78a5)
![Screenshot_20240624_194509_cgeo](https://github.com/opencaching/opencaching-pl/assets/173948046/52f097cf-f5ab-4eaa-bf85-b1a0c0be6700)

**Comment by deg-pl** [comment] 2024-06-26 20:41
It isn't OC PL code related problem, but site/user related.

**Comment by mzylowski** [comment] 2024-06-27 04:22
@deg-pl I'm so surprised by your answer from above, and also I just read the Facebook discussion with @pawelko-g about this issue. This is so technically incorrect from so many points of view that I'm shocked you're still pushing for this approach.

The rate limits you introduced to the OC server are an undocumented breaking change for OKAPI. @pawelko-g was using c:geo before your changes, but now you blame him for making too much traffic to the OCPL server. 
He is just an end-user of the opencaching site, and he sends his requests via the C: Geo app that he downloaded from Google Play. Why are you expecting the end user to stick to those limits just by using the app?

The 'actor' responsible for the violation of those rate limits is not pawelko, but the application (in this ticket it is c:geo, but there are a lot of others app affected by your change now). If you @deg-pl want to still keep these rate limits, you need to at least communicate about them to all OKAPI developers and at least add info about them to OKAPI documentation. However, the effort that needs to be made on the apps developer side to make possible use of opencaching date is so extreamlly huge (moving calling okapi to separate threads, some sleeps to avoid your limits etc), that I believe they need some time before those rate limits will be introduced. For now, you should do the rollback of those changes.

My proposal to mitigate the issue:
* Exclude OKAPI endpoints from those rate-limiting (long term solution)

Short-term solutions if you still want to keep those ridiculous limits:
* Add documentation for OKAPI description of your breaking change.
* Communicate 
* Create a new endpoint to OKAPI or add some more info to the existing one (i.e https://opencaching.pl/okapi/services/apisrv/stats.html) and allow developers to get the allowed number of requests. Maybe @wrygiel has an idea?
* Exclude our biggest customers from those limits for now, like c:geo, to give them time to apply needed code changes.

As long as OCPL end users are banned due to those limits, this is a high-priority issue caused by a misconfiguration of the OCPL server.

**Comment by deg-pl** [comment] 2024-06-27 05:42
@pawelko-g is the only user I know who has such a problem with c:geo.
If the problem is actually related to limiting the number of queries, it is still not a problem related to the OC PL code.

**Comment by mzylowski** [comment] 2024-06-27 05:56
@pawelko-g is the only user who reported this issue. The other users don't know what to do, and blame c:geo for hanging the update procedure.

**Comment by deg-pl** [comment] 2024-06-27 05:59
@pawelko-g started a discussion on Facebook in the OC group, but no one else confirmed the problem.

**Comment by mzylowski** [comment] 2024-06-27 05:59
Devon reproduction from my side 
![Screenshot_2024-06-27-07-57-27-775_cgeo.geocaching.jpg](https://github.com/opencaching/opencaching-pl/assets/13780868/4bc6c06d-cc74-4196-a69e-bf9d228a319d)

Now you will take responsibility for your changes?

**Comment by deg-pl** [comment] 2024-06-27 06:02
@mzylowski Please provide steps to reproduce the problem

**Comment by mzylowski** [comment] 2024-06-27 06:05
1. Download GPX for GeoPath (50 caches will be enough for sure) -> https://opencaching.pl/powerTrail.php?ptAction=showSerie&ptrail=912
2. Import downloaded GPX to c:geo
3. Refresh list of geocaches

**Comment by stefopl** [comment] 2024-06-27 06:17
A quick test:
I'm using the map to download caches in my area.
I have 200 caches to download offline, in my case it looked like this:
* 48 and failure in c:geo

When downloading, I can select the option in c:geo to do nothing with the downloaded caches and continue downloading more.
* 12 and failure
* 4 and failure
* 22 and failure

 When refreshing 200 caches, I don’t have this option, so it always ends in an error.
 
 I believe that at least 200 caches should be downloadable without a limit. When traveling to a new area for events with new geopaths, one typically needs to download around this number of caches.

**Comment by deg-pl** [comment] 2024-06-27 06:22
Thanks @mzylowski. 
Now I can reproduce problem. This makes it much easier to find a solution.

Server logs indicate that, in addition to OKAPI queries, images are being downloaded en masse to caches. The logs also indicate that the real limits are lower than those I configured (both the number of queries and the time unit in which it is tracked).

**Comment by deg-pl** [comment] 2024-06-27 07:07
@pawelko-g @mzylowski @stefopl Could you please check again?
Now the limiter seems to behave in accordance with the assumed configuration.

**Comment by stefopl** [comment] 2024-06-27 07:22
@deg-pl 
I intentionally chose more. Download completed successfully 264/264.
Thanks

**Comment by mzylowski** [comment] 2024-06-27 07:30
After your intervention I was able to successfully refresh entire 'Rowerowe Pomorze' geopath (the biggest GP in our service) 


![Screenshot_2024-06-27-09-22-16-685_cgeo.geocaching.jpg](https://github.com/opencaching/opencaching-pl/assets/13780868/c02b7218-8f09-4cd4-a55c-f02853779b8e)



![Screenshot_2024-06-27-09-27-13-027_com.synology.projectkailash.jpg](https://github.com/opencaching/opencaching-pl/assets/13780868/254437f9-bfc3-4983-8407-9ea445410d84)

Thanks!

How the limits are set currently?

**Comment by deg-pl** [comment] 2024-06-27 07:55
There are two limits:
- "single page" limit (number of views of a single page/one OKAPI endpoint calls per second): 150/s
- "entire site" limit: 200 views/s

The first limiter did not work properly and took the default value (5) instead of the one I set.

**Comment by pawelko-g** [comment] 2024-06-27 15:49
@deg-pl  @mzylowski @stefopl Thank you for your help. It also works fine for me now.

**Closed as completed** 2024-06-27 15:50 UTC
Labels: Priority High, Server Administration, Component Configs, Component OKAPI usage

**Comment by andrixnet** [comment] 2024-06-28 05:26
> There are two limits:
> 
>     * "single page" limit (number of views of a single page/single OKAPI endpoint calls per second): 150/s
> 
>     * "entire site" limit: 200 views/s
> 
> 
> The first limiter did not work properly and took the default value (5) instead of the one I set.

Where/how are these limits configurable per OC site?

**Comment by deg-pl** [comment] 2024-06-28 06:26
@andrixnet These limits are not OC PL code related. We use "evasive" as additional Apache2 module.
